export const DEFAULT_ZONES = [
  "Sala",
  "Comedor",
  "Cocina",
  "Habitación principal",
  "Habitación secundaria",
  "Baño principal",
  "Baño auxiliar",
  "Zona de ropas",
  "Balcón",
  "Parqueadero",
  "Cuarto útil",
  "Otro",
] as const;

export const DEFAULT_ITEMS_BY_ZONE: Record<string, string[]> = {
  Cocina: [
    "Mesón",
    "Lavaplatos",
    "Grifería",
    "Muebles superiores",
    "Muebles inferiores",
    "Estufa",
    "Horno",
    "Extractor",
  ],
  Baño: ["Sanitario", "Lavamanos", "Ducha", "Grifería", "Espejo", "Mueble", "Puerta"],
  Habitación: ["Puerta", "Ventana", "Clóset", "Piso", "Paredes", "Techo"],
  General: ["Piso", "Paredes", "Techo", "Puertas", "Ventanas", "Lámparas", "Tomas eléctricas", "Interruptores"],
};

export const GUIDED_ZONE_OPTIONS = [
  "Fachada o entrada",
  "Sala",
  "Comedor",
  "Cocina",
  "Habitación principal",
  "Habitación secundaria",
  "Habitación adicional",
  "Baño principal",
  "Baño auxiliar",
  "Zona de ropas",
  "Patio",
  "Balcón",
  "Terraza",
  "Garaje o parqueadero",
  "Cuarto útil",
  "Depósito",
  "Escaleras",
  "Pasillos",
  "Zonas comunes entregadas con el inmueble",
  "Medidores",
  "Llaves y controles",
  "Otros",
] as const;

export const GUIDED_ITEMS_BY_ZONE: Record<string, string[]> = {
  Cocina: [
    "Mesón",
    "Lavaplatos",
    "Grifería",
    "Muebles superiores",
    "Muebles inferiores",
    "Estufa",
    "Horno",
    "Campana o extractor",
    "Piso",
    "Paredes",
    "Techo",
    "Tomas eléctricas",
    "Iluminación",
    "Puerta",
    "Ventana",
  ],
  Baño: [
    "Sanitario",
    "Lavamanos",
    "Ducha",
    "Grifería",
    "Espejo",
    "Mueble",
    "Divisiones",
    "Piso",
    "Paredes",
    "Techo",
    "Puerta",
    "Ventana",
    "Desagües",
    "Iluminación",
  ],
  Habitaciones: [
    "Puerta",
    "Ventana",
    "Clóset",
    "Piso",
    "Paredes",
    "Techo",
    "Tomas eléctricas",
    "Interruptores",
    "Iluminación",
  ],
  "Sala / comedor": [
    "Piso",
    "Paredes",
    "Techo",
    "Ventanas",
    "Puertas",
    "Tomas eléctricas",
    "Interruptores",
    "Iluminación",
    "Cortinas o persianas si aplica",
  ],
  "Zona de ropas": [
    "Lavadero",
    "Grifería",
    "Conexión lavadora",
    "Desagüe",
    "Piso",
    "Paredes",
    "Ventilación",
    "Medidor o calentador si aplica",
  ],
  "Garaje o parqueadero": [
    "Piso",
    "Paredes",
    "Portón",
    "Control remoto si aplica",
    "Señalización",
    "Estado general",
  ],
};

